### ISSUE TITLE
Auto generated  XPath  can be shortened by removing /html 

### ISSUE THREAD

**Issue by pragmatictesters** [ranorex/selocity-extension#2]
Following XPath is generated by Seleocity automatically for an input field in a login page.
/html//input[@id='txtUsername']

It would better if /html prefix is not included into the XPath to make it shorter.

**Comment by zewa666** [comment]
Hi @pragmatictesters, well in order to have a valid XPath, you do need to have an anchor specified. Typically this would be the documents first child the `html` element. Alternatively you can use the descendent selector `//`.

So not really a lot we can do about it. Where and how are you using non-prefixed XPaths?

**Comment by rxse** [comment]
No reply from user in several months, and behavior works as designed. Closing.

**Comment by pragmatictesters** [comment]
Should be fine. Sorry for the late reply
