### ISSUE TITLE
Selocity will not connect to Webtestit

### ISSUE THREAD

**Issue by donrc12345** [ranorex/selocity-extension#6]
Just installed Webtestit and got the Chrome Selocity extension, but it will not connect to Webtestit.

**Comment by donrc12345** [comment]
Found a comment about instlling the Nightly dev release, but still have the same issue.

**Comment by rxse** [comment]
Hello @donrc12345!
This might happen if something is already using the port 3000.  Please check with the following command: `netstat -ano | findstr :3000` and see if there are some processes using it and try to kill them by using the process id (PID). If you are a Linux or a macOS user the command would be `lsof -i :3000`.  Start Ranorex Webtestit afterward and get the latest Ranorex Selocity extension and please try to connect again.

**Comment by donrc12345** [comment]
Here is the result of the command you suggested:
C:\Users\drclark>netstat -ano | findstr :3000
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       7724
  TCP    [::]:3000              [::]:0                 LISTENING       7724

I don't see anything there, but still will not connect.

**Comment by rxse** [comment]
Hi again @donrc12345!

Have you executed that command while Ranorex Webtestit was running, or have you close it first? 
Can you try the following - Close Ranorex Webtestit, kill all Google Chrome processes ( this can be easily done with `taskkill /IM chrome.exe /F`), start Ranorex Webtestit again and try to connect the extension. If the issue persists, maybe we could arrange a short skype meeting so that we can take a closer look at what seems to be an issue, and try to solve it?
If you are comfortable with that, please let us know and contact us at our support-webtestit@ranorex.com mailbox.

**Comment by donrc12345** [comment]
I installed TCPView and found that grafana-server.exe was using port 3000.  I disabled that and the Selocity extension is connecting to Webtestit now.  Thank you for your help!

**Comment by zewa666** [comment]
Thanks for digging into the issue @donrc12345. We'll make sure to add a fix for that as typically Ranorex Webtestit should negotiate for a free port >=3000
